// I-84 — embedded font metrics for IColumn.AutoSize on the Open XML SDK engine.
//
// The SDK engine measures text with embedded numeric advance-width tables
// extracted from openly-licensed, metric-compatible fonts (Carlito ↔ Calibri,
// Liberation Sans/Serif/Mono ↔ Arial/Times New Roman/Courier New) — zero
// runtime font dependency, deterministic across environments, headless-safe,
// AOT-clean. Tables live in FontMetricsTables.g.cs (generated by
// tools/FontMetricsGen; provenance in its header). Fonts with no metric table
// throw MissingFontException — fail loud, never silently-wrong widths (the
// I-3 contract, now environment-independent).
//
// The width math mirrors NPOI 2.7.3's SheetUtil (oracle-dumped 2026-06-03):
//   defaultCharWidth = ceil(inkWidth('0') of font index 0, px @96dpi)
//   actualWidth      = round(measured line width px, MidpointRounding.ToEven)
//   cellWidth        = (actualWidth + 5) / defaultCharWidth * 1.05 + indent
// with one deliberate approximation: NPOI measures the ink bounding box
// (SixLabors MeasureSize); this engine sums per-char advances, which runs
// ~1px wide of the ink box (no kerning, no first/last side-bearing trim).
// Cross-engine width parity is therefore TOLERANCE-based, not exact.

using System;

namespace NetXlsx;

/// <summary>The embedded metric families (see FontMetricsTables.g.cs).</summary>
internal enum MetricFamily
{
    Carlito,
    LiberationSans,
    LiberationSerif,
    LiberationMono,
}

/// <summary>
/// The effective style axes AutoSize measurement needs for one cell:
/// resolved font name/size/bold/italic plus alignment indent and the raw
/// OOXML text rotation (0–180). Produced by OoxmlStylePool.AutoSizeStyleOf.
/// </summary>
internal readonly record struct AutoSizeStyle(
    string FontName, double FontSize, bool Bold, bool Italic, int Indent, int RotationRaw);

/// <summary>
/// One font variant's numeric metrics: per-char advance widths in font units
/// plus the '0' glyph ink width and ascent/descent (all unitsPerEm-relative).
/// </summary>
internal sealed class FontMetricsTable
{
    private readonly ushort[] _advances;        // U+0020..U+00FF; 0 = unmapped
    private readonly ushort[] _extraAdvances;   // parallel to FontMetricsTables.ExtraChars

    internal int UnitsPerEm { get; }
    internal int DigitInk { get; }
    internal int Ascent { get; }
    internal int Descent { get; }

    internal FontMetricsTable(int unitsPerEm, int digitInk, int ascent, int descent,
        ushort[] advances, ushort[] extraAdvances)
    {
        UnitsPerEm = unitsPerEm;
        DigitInk = digitInk;
        Ascent = ascent;
        Descent = descent;
        _advances = advances;
        _extraAdvances = extraAdvances;
    }

    // Unmapped chars fall back to the digit advance — a deterministic middle
    // ground (documented I-84 approximation; NPOI renders the font's .notdef).
    internal int AdvanceUnitsOf(char ch)
    {
        if (ch is >= ' ' and <= 'ÿ')
        {
            int a = _advances[ch - ' '];
            if (a > 0) return a;
        }
        else
        {
            int i = Array.IndexOf(FontMetricsTables.ExtraChars, ch);
            if (i >= 0 && _extraAdvances[i] > 0) return _extraAdvances[i];
        }
        return _advances['0' - ' '];
    }
}

internal static class OoxmlFontMetrics
{
    // NPOI's SheetUtil measures at a fixed 96 dpi.
    private const double PxPerPoint = 96.0 / 72.0;

    /// <summary>
    /// Resolves a font name + style to its embedded metric table, or throws
    /// <see cref="MissingFontException"/> for fonts outside the embedded set.
    /// </summary>
    internal static FontMetricsTable Resolve(string fontName, bool bold, bool italic)
    {
        var family = TryFamilyOf(fontName);
        if (family is null)
            throw new MissingFontException(
                $"IColumn.AutoSize() has no embedded font metrics for '{fontName}'. " +
                "The Open XML SDK engine measures text with embedded metric tables (decision I-84) covering: " +
                "Calibri/Carlito/Aptos, Arial/Liberation Sans/Arimo/Helvetica, " +
                "Times New Roman/Liberation Serif/Tinos, and Courier New/Liberation Mono/Cousine. " +
                "For other fonts, set the width explicitly via IColumn.Width(double).");
        return FontMetricsTables.GetTable(family.Value, bold, italic);
    }

    // Metric-twin name mapping, case-insensitive. Aptos (the modern Office
    // default) has no open metric twin yet — Carlito is the documented
    // best-effort stand-in (I-84). Arial Narrow is deliberately absent:
    // Liberation 1.x's Narrow is GPL-lineage (see tools/FontMetricsGen/README.md).
    private static MetricFamily? TryFamilyOf(string fontName)
    {
        string key = fontName.Trim();
        if (Is(key, "Calibri") || Is(key, "Carlito") || Is(key, "Aptos") || Is(key, "Aptos Narrow"))
            return MetricFamily.Carlito;
        if (Is(key, "Arial") || Is(key, "Liberation Sans") || Is(key, "Arimo") || Is(key, "Helvetica"))
            return MetricFamily.LiberationSans;
        if (Is(key, "Times New Roman") || Is(key, "Liberation Serif") || Is(key, "Tinos"))
            return MetricFamily.LiberationSerif;
        if (Is(key, "Courier New") || Is(key, "Liberation Mono") || Is(key, "Cousine"))
            return MetricFamily.LiberationMono;
        return null;

        static bool Is(string name, string candidate)
            => string.Equals(name, candidate, StringComparison.OrdinalIgnoreCase);
    }

    /// <summary>
    /// Sum-of-advances width of one line in pixels at 96 dpi — UNROUNDED;
    /// the caller applies NPOI's MidpointRounding.ToEven at the same point
    /// in the formula NPOI does.
    /// </summary>
    internal static double MeasureLineRawPx(FontMetricsTable table, string line, double sizePoints)
    {
        long units = 0;
        foreach (char ch in line)
            units += table.AdvanceUnitsOf(ch);
        return units / (double)table.UnitsPerEm * sizePoints * PxPerPoint;
    }

    /// <summary>
    /// NPOI's defaultCharWidth: the ink width of '0' in the workbook's default
    /// font, in pixels at 96 dpi, ceiling-rounded to an integer.
    /// </summary>
    internal static int DefaultCharWidthPx(FontMetricsTable table, double sizePoints)
        => (int)Math.Ceiling(table.DigitInk / (double)table.UnitsPerEm * sizePoints * PxPerPoint);

    /// <summary>
    /// Line-height proxy for rotated-cell measurement (ascent − descent, px
    /// at 96 dpi, unrounded). NPOI uses the rotated string's ink-box height;
    /// this over-approximates slightly — columns come out marginally wide,
    /// never clipped (documented I-84 approximation).
    /// </summary>
    internal static double ApproxLineHeightRawPx(FontMetricsTable table, double sizePoints)
        => (table.Ascent - (double)table.Descent) / table.UnitsPerEm * sizePoints * PxPerPoint;
}
