// FontMetricsGen — extracts numeric advance-width tables from openly-licensed,
// metric-compatible TrueType fonts and emits them as C# source for NetXlsx's
// IColumn.AutoSize on the Open XML SDK engine (decision I-84).
//
// Only NUMBERS are extracted (per-char advance widths, the '0' glyph's ink
// width, ascent/descent, unitsPerEm) — never font-file bytes or outlines —
// so NetXlsx's MIT licensing posture is unaffected. Sources must be openly
// licensed (OFL); never extract from proprietary fonts (e.g. msttcorefonts).
//
// Usage: dotnet run --project tools/FontMetricsGen [-- <fontsRoot> <outputPath>]
//   fontsRoot   default /usr/share/fonts/truetype
//   outputPath  default src/NetXlsx/Internal/FontMetricsTables.g.cs (repo-relative)

using System.Buffers.Binary;
using System.Globalization;
using System.Security.Cryptography;
using System.Text;

string fontsRoot = args.Length > 0 ? args[0] : "/usr/share/fonts/truetype";
string outputPath = args.Length > 1
    ? args[1]
    : Path.Combine(FindRepoRoot(), "src", "NetXlsx", "Internal", "FontMetricsTables.g.cs");

// (family key, style key, relative font path). Family/style keys must match
// the FontMetricsTables.GetTable switch emitted below and the resolver in
// src/NetXlsx/Internal/OoxmlFontMetrics.cs.
(string Family, string Style, string Path)[] sources =
[
    ("Carlito", "Regular", "crosextra/Carlito-Regular.ttf"),
    ("Carlito", "Bold", "crosextra/Carlito-Bold.ttf"),
    ("Carlito", "Italic", "crosextra/Carlito-Italic.ttf"),
    ("Carlito", "BoldItalic", "crosextra/Carlito-BoldItalic.ttf"),
    ("LiberationSans", "Regular", "liberation2/LiberationSans-Regular.ttf"),
    ("LiberationSans", "Bold", "liberation2/LiberationSans-Bold.ttf"),
    ("LiberationSans", "Italic", "liberation2/LiberationSans-Italic.ttf"),
    ("LiberationSans", "BoldItalic", "liberation2/LiberationSans-BoldItalic.ttf"),
    ("LiberationSerif", "Regular", "liberation2/LiberationSerif-Regular.ttf"),
    ("LiberationSerif", "Bold", "liberation2/LiberationSerif-Bold.ttf"),
    ("LiberationSerif", "Italic", "liberation2/LiberationSerif-Italic.ttf"),
    ("LiberationSerif", "BoldItalic", "liberation2/LiberationSerif-BoldItalic.ttf"),
    ("LiberationMono", "Regular", "liberation2/LiberationMono-Regular.ttf"),
    ("LiberationMono", "Bold", "liberation2/LiberationMono-Bold.ttf"),
    ("LiberationMono", "Italic", "liberation2/LiberationMono-Italic.ttf"),
    ("LiberationMono", "BoldItalic", "liberation2/LiberationMono-BoldItalic.ttf"),
];

// Chars covered: the contiguous U+0020..U+00FF block (ASCII + Latin-1
// Supplement) plus a short list of common typographic characters. Everything
// else falls back to the digit advance at measure time.
char[] extraChars =
[
    '–', '—', '‘', '’', '“', '”',
    '•', '…', '€', '™', '−',
];

var sb = new StringBuilder();
sb.AppendLine("// <auto-generated/>");
sb.AppendLine("// Embedded font-metric tables for IColumn.AutoSize on the Open XML SDK engine");
sb.AppendLine("// (decision I-84). Generated by tools/FontMetricsGen — do not edit by hand.");
sb.AppendLine("//");
sb.AppendLine("// Data provenance (numeric metrics only; no font-file bytes are embedded):");

var tableDecls = new StringBuilder();
var switchArms = new StringBuilder();

foreach (var (family, style, rel) in sources)
{
    string path = Path.Combine(fontsRoot, rel);
    byte[] bytes = File.ReadAllBytes(path);
    var ttf = new TrueTypeFont(bytes);

    string sha = Convert.ToHexString(SHA256.HashData(bytes)).ToLowerInvariant();
    sb.AppendLine(CultureInfo.InvariantCulture, $"//   {rel} (sha256 {sha[..16]}…) — \"{ttf.FullName}\"");

    ushort[] advances = new ushort[256 - 32];
    for (int c = 32; c <= 255; c++)
        advances[c - 32] = ttf.AdvanceOf((char)c);
    ushort[] extras = new ushort[extraChars.Length];
    for (int i = 0; i < extraChars.Length; i++)
        extras[i] = ttf.AdvanceOf(extraChars[i]);

    string id = family + style;
    tableDecls.AppendLine(CultureInfo.InvariantCulture, $"    private static readonly FontMetricsTable {id} = new(");
    tableDecls.AppendLine(CultureInfo.InvariantCulture, $"        unitsPerEm: {ttf.UnitsPerEm}, digitInk: {ttf.DigitInkWidth}, ascent: {ttf.Ascent}, descent: {ttf.Descent},");
    tableDecls.AppendLine(CultureInfo.InvariantCulture, $"        advances: [{string.Join(", ", advances)}],");
    tableDecls.AppendLine(CultureInfo.InvariantCulture, $"        extraAdvances: [{string.Join(", ", extras)}]);");
    tableDecls.AppendLine();

    string bold = style is "Bold" or "BoldItalic" ? "true" : "false";
    string italic = style is "Italic" or "BoldItalic" ? "true" : "false";
    switchArms.AppendLine(CultureInfo.InvariantCulture, $"            (MetricFamily.{family}, {bold}, {italic}) => {id},");
}

sb.AppendLine("//");
sb.AppendLine("// Carlito: SIL OFL 1.1 (c) tyPoland Lukasz Dziedzic — metric-compatible with Calibri.");
sb.AppendLine("// Liberation Sans/Serif/Mono 2.x: SIL OFL 1.1 (c) Red Hat / Google — metric-");
sb.AppendLine("// compatible with Arial / Times New Roman / Courier New.");
sb.AppendLine();
sb.AppendLine("namespace NetXlsx;");
sb.AppendLine();
sb.AppendLine("internal static partial class FontMetricsTables");
sb.AppendLine("{");
sb.AppendLine("    // Common typographic chars outside U+0020..U+00FF carried by every table.");
sb.AppendLine(CultureInfo.InvariantCulture, $"    internal static readonly char[] ExtraChars = [{string.Join(", ", extraChars.Select(c => $"'\\u{(int)c:X4}'"))}];");
sb.AppendLine();
sb.Append(tableDecls);
sb.AppendLine("    internal static FontMetricsTable GetTable(MetricFamily family, bool bold, bool italic)");
sb.AppendLine("        => (family, bold, italic) switch");
sb.AppendLine("        {");
sb.Append(switchArms);
sb.AppendLine("            _ => throw new System.ArgumentOutOfRangeException(nameof(family)),");
sb.AppendLine("        };");
sb.AppendLine("}");

File.WriteAllText(outputPath, sb.ToString());
Console.WriteLine($"Wrote {outputPath} ({sources.Length} tables).");

static string FindRepoRoot()
{
    var dir = new DirectoryInfo(AppContext.BaseDirectory);
    for (var d = dir; d is not null; d = d.Parent)
        if (File.Exists(Path.Combine(d.FullName, "NetXlsx.sln")))
            return d.FullName;
    // Fallback: assume cwd is the repo root (dotnet run from repo root).
    return Directory.GetCurrentDirectory();
}

// Minimal big-endian TrueType reader: head/hhea/maxp/hmtx/cmap (format 4) and
// the glyf bbox of '0' (for NPOI's ink-width defaultCharWidth divisor).
internal sealed class TrueTypeFont
{
    private readonly byte[] _b;
    private readonly Dictionary<string, (int Offset, int Length)> _tables = new(StringComparer.Ordinal);
    private readonly int _numberOfHMetrics;
    private readonly int _numGlyphs;
    private readonly bool _longLoca;
    private readonly int _cmapSubtable;   // absolute offset of the format-4 subtable

    public ushort UnitsPerEm { get; }
    public short Ascent { get; }
    public short Descent { get; }
    public ushort DigitInkWidth { get; }
    public string FullName { get; }

    public TrueTypeFont(byte[] bytes)
    {
        _b = bytes;
        int numTables = U16(4);
        for (int i = 0; i < numTables; i++)
        {
            int rec = 12 + 16 * i;
            string tag = Encoding.ASCII.GetString(bytes, rec, 4);
            _tables[tag] = ((int)U32(rec + 8), (int)U32(rec + 12));
        }

        int head = Off("head");
        UnitsPerEm = U16(head + 18);
        _longLoca = S16(head + 50) == 1;

        int hhea = Off("hhea");
        Ascent = S16(hhea + 4);
        Descent = S16(hhea + 6);
        _numberOfHMetrics = U16(hhea + 34);

        _numGlyphs = U16(Off("maxp") + 4);
        _cmapSubtable = FindCmapFormat4();
        FullName = ReadName(4) ?? ReadName(1) ?? "?";

        int zeroGlyph = GlyphOf('0');
        DigitInkWidth = zeroGlyph > 0 ? InkWidthOf(zeroGlyph) : (ushort)0;
        if (DigitInkWidth == 0)
            throw new InvalidDataException("no ink width for '0' — wrong font file?");
    }

    public ushort AdvanceOf(char c)
    {
        int glyph = GlyphOf(c);
        if (glyph == 0) return 0;   // unmapped — resolver falls back at measure time
        int hmtx = Off("hmtx");
        int i = Math.Min(glyph, _numberOfHMetrics - 1);
        return U16(hmtx + 4 * i);
    }

    private int GlyphOf(char c)
    {
        int sub = _cmapSubtable;
        int segCount = U16(sub + 6) / 2;
        int endCodes = sub + 14;
        int startCodes = endCodes + segCount * 2 + 2;
        int idDeltas = startCodes + segCount * 2;
        int idRangeOffsets = idDeltas + segCount * 2;
        for (int i = 0; i < segCount; i++)
        {
            int end = U16(endCodes + 2 * i);
            if (c > end) continue;
            int start = U16(startCodes + 2 * i);
            if (c < start) return 0;
            int idRangeOffset = U16(idRangeOffsets + 2 * i);
            if (idRangeOffset == 0)
                return (c + S16(idDeltas + 2 * i)) & 0xFFFF;
            int addr = idRangeOffsets + 2 * i + idRangeOffset + 2 * (c - start);
            int g = U16(addr);
            return g == 0 ? 0 : (g + S16(idDeltas + 2 * i)) & 0xFFFF;
        }
        return 0;
    }

    private ushort InkWidthOf(int glyph)
    {
        if (glyph >= _numGlyphs) return 0;
        int loca = Off("loca");
        long start, end;
        if (_longLoca) { start = U32(loca + 4 * glyph); end = U32(loca + 4 * (glyph + 1)); }
        else { start = U16(loca + 2 * glyph) * 2L; end = U16(loca + 2 * (glyph + 1)) * 2L; }
        if (end <= start) return 0;   // empty glyph
        int g = Off("glyf") + (int)start;
        short xMin = S16(g + 2), xMax = S16(g + 6);
        return (ushort)(xMax - xMin);
    }

    private int FindCmapFormat4()
    {
        int cmap = Off("cmap");
        int n = U16(cmap + 2);
        int best = -1;
        for (int i = 0; i < n; i++)
        {
            int rec = cmap + 4 + 8 * i;
            int platform = U16(rec), encoding = U16(rec + 2);
            int sub = cmap + (int)U32(rec + 4);
            if (U16(sub) != 4) continue;
            if (platform == 3 && encoding == 1) return sub;       // Windows BMP — preferred
            if (best < 0 && (platform == 0 || platform == 3)) best = sub;
        }
        return best >= 0 ? best : throw new InvalidDataException("no format-4 cmap subtable");
    }

    private string? ReadName(int nameId)
    {
        if (!_tables.ContainsKey("name")) return null;
        int name = Off("name");
        int count = U16(name + 2);
        int strings = name + U16(name + 4);
        for (int i = 0; i < count; i++)
        {
            int rec = name + 6 + 12 * i;
            if (U16(rec + 6) != nameId) continue;
            int platform = U16(rec);
            int len = U16(rec + 8), off = strings + U16(rec + 10);
            if (platform == 3)
                return Encoding.BigEndianUnicode.GetString(_b, off, len);
            return Encoding.ASCII.GetString(_b, off, len);
        }
        return null;
    }

    private int Off(string tag) => _tables.TryGetValue(tag, out var t)
        ? t.Offset
        : throw new InvalidDataException($"missing table {tag}");

    private ushort U16(int o) => BinaryPrimitives.ReadUInt16BigEndian(_b.AsSpan(o, 2));
    private short S16(int o) => BinaryPrimitives.ReadInt16BigEndian(_b.AsSpan(o, 2));
    private uint U32(int o) => BinaryPrimitives.ReadUInt32BigEndian(_b.AsSpan(o, 4));
}
